import PreviewPage from "@/components/views/articles/previewArticles";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    template: "%s | Web Blog",
    default: "Articles ",
  },
  description: "Generated by create next app",
};

export default function Articles() {
  return <PreviewPage />;
}
