import type { Metadata } from "next";
import ArticleForm from "../../../components/views/articles/formArticles";

export const metadata: Metadata = {
  title: {
    template: "Articles ",
    default: "Articles - Edit Article",
  },
  description: "Generated by create next app",
};

export default function ArticlesPage() {
  return (
    <section>
      <ArticleForm />
    </section>
  );
}
