import type { Metadata } from "next";
import Category from "@/components/views/category/categoryPage";
import LayoutProvider from "@/components/layout/layoutProvider";
export const metadata: Metadata = {
  title: {
    template: "Category %s",
    default: "Category ",
  },
  description: "Generated by create next app",
};

export default function CategoryPage() {
  return (
    <LayoutProvider>
      <Category />
    </LayoutProvider>
  );
}
