import type { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    template: "%s | Web Blog",
    default: "Register",
  },
  description: "Generated by create next app",
};

export default function RegisterLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <>{children}</>;
}
